source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PLMScrollMenu_Example', :exclusive => true do
  pod 'PLMScrollMenu', :path => '../'
end

target 'PLMScrollMenu_Tests', :exclusive => true do
  pod 'PLMScrollMenu', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  #pod 'FBSnapshotTestCase'
  #pod 'Nimble-Snapshots'
  
end
